# Site settings
title: Keiven Adrian Busita
email: kadbusita@gmail.com
url: https://kadbusita.github.io
description: "Check my working experience as a back-end developer!"
keywords: "backend, webservices, soa, api development"
skills: "Application Developer - Web Services / SOA"
meta_author: Keiven Adrian Busita

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Keiven Adrian Busita
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/musickebbin
  - title: facebook
    url: https://www.facebook.com/kadbusita.itpro
  - title: stack-overflow
    url: https://forums.mulesoft.com/users/13646/kadbusita.html
  - title: bitbucket
    url: https://github.com/kadbusita

# Postal address (add as many lines as necessary)
address:
  - line: 455 Gen. Yengco Street B.S.
  - line: Quezon City, Philippines, 1119

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty
